import {NextRequest,NextResponse} from 'next/server';
import {Agent,run,tool} from '@openai/agents';
import {z} from 'zod';
import {userSupabase} from '@/lib/supabase';
import {demoOrders} from '@/lib/demo';
export const runtime='nodejs';export const maxDuration=60;
const RouteDecision=z.object({tier:z.enum(['economy','balanced','advanced']),reason:z.string(),risk:z.enum(['low','medium','high']),expectedTools:z.array(z.enum(['orders','exceptions','quality']))});
const MODEL_PORTFOLIO={economy:'gpt-5.6-luna',balanced:'gpt-5.6-terra',advanced:'gpt-5.6-sol'} as const;
export async function POST(req:NextRequest){const started=Date.now();try{if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:'Brak OPENAI_API_KEY.'},{status:503});const {question,demo}=await req.json();if(!String(question||'').trim())return NextResponse.json({error:'Wpisz pytanie.'},{status:400});const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');let sb:ReturnType<typeof userSupabase>|null=null;if(!demo){if(!token)return NextResponse.json({error:'Wymagane logowanie.'},{status:401});sb=userSupabase(token);const {data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:'Sesja wygasła.'},{status:401})}
 const router=new Agent({name:'Agent router modeli',model:'gpt-5.6-luna',outputType:RouteDecision,instructions:'Oceń zadanie przed analizą. economy: proste podsumowanie lub jedno zapytanie. balanced: analiza kilku danych, ryzyko lub finanse. advanced: wieloetapowa analiza strategiczna, scenariusze, niejednoznaczność albo decyzja o wysokim wpływie. Wybierz najtańszy poziom, który zapewni rzetelność. Nie rozwiązuj zadania — zwróć wyłącznie decyzję routingu.'});
 const routingRun=await run(router,String(question).slice(0,2000),{maxTurns:2});const routing=RouteDecision.parse(routingRun.finalOutput);const selectedModel=MODEL_PORTFOLIO[routing.tier];
 const calls:string[]=[];
 const ordersSummary=tool({name:'orders_summary',description:'Pobiera zagregowane zamówienia i wysyłki według klientów. Używaj do każdej analizy realizacji.',parameters:z.object({limit:z.number().int().min(1).max(100).default(30)}),execute:async({limit})=>{calls.push('orders_summary');if(demo)return demoOrders.slice(0,limit);const {data,error}=await sb!.from('order_fulfilment').select('*').limit(limit);if(error)throw error;return data}});
 const exceptions=tool({name:'delivery_exceptions',description:'Pobiera największe niedowozy i zamówienia wymagające interwencji.',parameters:z.object({limit:z.number().int().min(1).max(50).default(15)}),execute:async({limit})=>{calls.push('delivery_exceptions');if(demo)return demoOrders.filter(x=>x.shipped<x.ordered).slice(0,limit);const {data,error}=await sb!.from('order_fulfilment').select('*').gt('short_quantity',0).order('short_quantity',{ascending:false}).limit(limit);if(error)throw error;return data}});
 const dataQuality=tool({name:'data_quality_checks',description:'Sprawdza luki: wysyłki bez zamówień, brak ilości, waluty i duplikaty.',parameters:z.object({}),execute:async()=>{calls.push('data_quality_checks');if(demo)return {shipments_without_order:1,orders_without_currency:2,missing_quantity:0};const {data,error}=await sb!.rpc('data_quality_summary');if(error)throw error;return data}});
 const risk=new Agent({name:'Agent ryzyka',model:selectedModel,instructions:'Jesteś specjalistą ryzyka realizacji zamówień. Zawsze użyj narzędzia delivery_exceptions. Nadaj priorytet, podaj dowody liczbowe i nie nazywaj niedowozu utraconą sprzedażą bez potwierdzenia.',tools:[exceptions,ordersSummary]});
 const finance=new Agent({name:'Agent finansowy',model:selectedModel,instructions:'Jesteś kontrolerem finansowym. Użyj orders_summary. Oddziel fakty od szacunków, nie sumuj różnych walut i zaznacz brak ceny lub marży.',tools:[ordersSummary]});
 const quality=new Agent({name:'Agent jakości danych',model:selectedModel,instructions:'Jesteś audytorem danych. Uruchom data_quality_checks i wskaż kontrole naprawcze.',tools:[dataQuality]});
 const coordinator=new Agent({name:'Koordynator operacyjny',model:selectedModel,instructions:'Koordynujesz analizę zamówień i wysyłek. Sam wybierasz właściwego specjalistę jako narzędzie. Odpowiedź po polsku: najpierw 3 wnioski, następnie działania z właścicielem i terminem. Nie wymyślaj danych.',tools:[risk.asTool({toolName:'risk_specialist',toolDescription:'Deleguj analizę niedowozów, tolerancji i priorytetów ryzyka.'}),finance.asTool({toolName:'finance_specialist',toolDescription:'Deleguj analizę wartości, walut, marży i ekspozycji.'}),quality.asTool({toolName:'quality_specialist',toolDescription:'Deleguj kontrolę jakości i kompletności danych.'})]});
 const result=await run(coordinator,String(question).slice(0,2000),{maxTurns:8});if(sb)await sb.from('agent_runs').insert({question:String(question).slice(0,2000),router_model:'gpt-5.6-luna',selected_model:selectedModel,tier:routing.tier,risk:routing.risk,reason:routing.reason,tools:calls,latency_ms:Date.now()-started});return NextResponse.json({answer:String(result.finalOutput),agent:'Koordynator + specjaliści',model:selectedModel,routing,tools:calls,latencyMs:Date.now()-started});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Błąd systemu agentowego.'},{status:500})}}
