'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,Bot,BrainCircuit,Database,FileUp,LogOut,PackageCheck,ShieldAlert,Sparkles,Truck,TriangleAlert,Clock3} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {browserSupabase,configured} from '@/lib/supabase';

const fmt=(v:number)=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:1}).format(v||0);
const pct=(v:number|null)=>v==null?'—':new Intl.NumberFormat('pl-PL',{style:'percent',maximumFractionDigits:1}).format(v);
type Msg={role:'user'|'assistant';text:string;meta?:string};

export default function OperationsDashboard(){
 const [ready,setReady]=useState(!configured),[email,setEmail]=useState(''),[tab,setTab]=useState('overview'),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [from,setFrom]=useState('2026-01-01'),[to,setTo]=useState('2026-12-31'),[customer,setCustomer]=useState(''),[assessment,setAssessment]=useState('');
 const [messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'Jestem koordynatorem. Korzystam z tej samej warstwy obliczeń co dashboard: zamówienia, wysyłki, tolerancje, niedowozy i zamówienia bez wysyłki.'}]),[question,setQuestion]=useState('Podsumuj realizację zamówień od stycznia 2026 i wskaż największe ryzyka.'),[busy,setBusy]=useState(false),[importText,setImportText]=useState('');
 useEffect(()=>{const sb=browserSupabase();if(!sb)return;sb.auth.getUser().then(({data})=>{setEmail(data.user?.email||'');setReady(true)});const {data}=sb.auth.onAuthStateChange((_e,s)=>setEmail(s?.user.email||''));return()=>data.subscription.unsubscribe()},[]);
 async function refresh(){const sb=browserSupabase();if(!sb||!email)return;setLoading(true);setError('');try{const {data:s}=await sb.auth.getSession();const r=await fetch(`/api/analytics?from=${from}&to=${to}`,{headers:{Authorization:`Bearer ${s.session?.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Błąd danych')}finally{setLoading(false)}}
 useEffect(()=>{if(email)refresh()},[email]);
 async function login(e:string,p:string,signup=false){const sb=browserSupabase();if(!sb)return;const r=signup?await sb.auth.signUp({email:e,password:p}):await sb.auth.signInWithPassword({email:e,password:p});if(r.error)throw r.error}
 async function ask(){if(!question.trim()||busy)return;const q=question;setQuestion('');setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);try{const sb=browserSupabase();const {data:s}=await sb!.auth.getSession();const r=await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.session?.access_token}`},body:JSON.stringify({question:q,demo:false})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(m=>[...m,{role:'assistant',text:d.answer,meta:`${d.model} · ${d.tools?.join(' → ')||'analiza'} · ${d.latencyMs} ms`}])}catch(e){setMessages(m=>[...m,{role:'assistant',text:`Błąd analizy: ${e instanceof Error?e.message:'nieznany błąd'}`}])}finally{setBusy(false)}}
 async function importFiles(files:FileList|null){if(!files?.length)return;const sb=browserSupabase();const {data:s}=await sb!.auth.getSession();let rows=0;try{for(const file of Array.from(files)){setImportText(`Importuję ${file.name}…`);const form=new FormData();form.append('files',file);const r=await fetch('/api/import',{method:'POST',headers:{Authorization:`Bearer ${s.session?.access_token}`},body:form});const raw=await r.text();let d:any;try{d=JSON.parse(raw)}catch{throw new Error(`${file.name}: nieprawidłowa odpowiedź serwera (${r.status})`)}if(!r.ok)throw new Error(d.error||`Nie udało się wczytać ${file.name}`);rows+=Number(d.rows)||0}setImportText(`Zaimportowano ${fmt(rows)} rekordów.`);await refresh()}catch(e){setImportText(e instanceof Error?e.message:'Import nie powiódł się')}}
 const customers=useMemo(()=>[...new Set((data?.clients||[]).map((x:any)=>x.customer))].sort() as string[],[data]);
 const filter=(rows:any[])=>rows.filter(r=>(!customer||r.customer===customer)&&(!assessment||r.assessment===assessment));
 if(!ready)return <div className="splash"><BrainCircuit/>Łączenie z Supabase…</div>;
 if(configured&&!email)return <Login onLogin={login}/>;
 const k=data?.kpis||{};const nav:[string,any,string][]=[['overview',Activity,'Przegląd'],['lost',TriangleAlert,'Utracone sztuki'],['pending',Clock3,'Do wysłania'],['orders',PackageCheck,'Zamówienia'],['shipments',Truck,'Wysyłki'],['agents',Bot,'Agenci AI'],['data',Database,'Źródła danych']];
 return <main><aside><div className="brand"><span><BrainCircuit/></span><div>FlowControl<b>AI</b><small>Order intelligence</small></div></div><nav>{nav.map(([id,I,label]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={19}/>{label}</button>)}</nav><div className="asideBottom"><div className="security"><ShieldAlert size={17}/>RLS · {email}</div><button onClick={()=>browserSupabase()?.auth.signOut()}><LogOut size={18}/>Wyloguj</button></div></aside><section className="workspace"><header><div><p>OPERATIONS COMMAND CENTER</p><h1>{nav.find(x=>x[0]===tab)?.[2]}</h1></div><div className="headActions"><span className="live"><i/>{loading?'Przeliczanie…':'Dane z Supabase'}</span><label className="upload"><FileUp size={17}/>Importuj XLSX<input type="file" multiple accept=".xlsx,.xls" onChange={e=>importFiles(e.target.files)}/></label></div></header>
 {error&&<div className="importStatus error">{error}</div>}{tab!=='agents'&&tab!=='data'&&<div className="filterbar"><label>Od <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Do <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Klient <select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Wszyscy</option>{customers.map(x=><option key={x}>{x}</option>)}</select></label><label>Ocena <select value={assessment} onChange={e=>setAssessment(e.target.value)}><option value="">Wszystkie</option><option>W granicach</option><option>Poza granicą</option><option>Brak zdefiniowanych granic</option></select></label><button onClick={refresh}>Przelicz</button></div>}
 {tab==='overview'&&<><div className="freshness"><span>Ostatnie zamówienie: <b>{data?.freshness?.last_order?.slice(0,10)||'—'}</b></span><span>Ostatnia wysyłka: <b>{data?.freshness?.last_shipment?.slice(0,10)||'—'}</b></span><span>Zakres danych: <b>{from} – {to}</b></span></div><div className="kpis"><K label="Zamówiono" value={fmt(k.ordered_quantity)}/><K label="Wysłano" value={fmt(k.shipped_quantity)} good/><K label="Realizacja" value={pct(k.fulfilment_rate)}/><K label="Poza granicą" value={fmt(k.outside_limit)} warn/></div><div className="grid"><article className="chart card"><div className="cardTitle"><div><span>KLIENT × MIESIĄC</span><h2>Zamówienia i wysyłki</h2></div></div><ResponsiveContainer width="100%" height={300}><AreaChart data={data?.monthly||[]}><CartesianGrid stroke="#25293d" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip contentStyle={{background:'#151827',border:'1px solid #30344c'}}/><Area dataKey="ordered" name="Zamówiono" stroke="#8b5cf6" fill="#8b5cf633"/><Area dataKey="shipped" name="Wysłano" stroke="#23d3a7" fill="transparent"/></AreaChart></ResponsiveContainer></article><article className="card"><div className="cardTitle"><div><span>SYGNAŁY RYZYKA</span><h2>Klienci wymagający uwagi</h2></div></div>{(data?.clients||[]).slice(0,10).map((r:any)=><div className="client" key={r.customer}><i className="dot risk"/><div><b>{r.customer}</b><small>{fmt(r.lost_quantity)} szt. niedowozu</small></div><strong>{r.outside_limit} poza granicą</strong></div>)}</article></div></>}
 {tab==='lost'&&<DataTable title="Zamówienia z niedowozem" rows={filter(data?.lost||[])} columns={[['order_no','Zamówienie'],['customer','Klient'],['ordered_quantity','Zamówiono'],['shipped_quantity','Wysłano'],['lost_quantity','Utracone szt.'],['minimum_quantity','Dolna granica'],['lost_below_limit','Poniżej granicy'],['assessment','Ocena'],['order_date','Data zamówienia']]}/>} 
 {tab==='pending'&&<><div className="kpis"><K label="Bez wysyłki" value={fmt(k.pending_orders)}/><K label="Sztuk do wysłania" value={fmt(k.pending_quantity)} warn/><K label="Wysyłki niedopasowane" value={fmt(k.unmatched_shipments)}/><K label="Niedowozy" value={fmt(k.lost_quantity)} warn/></div><DataTable title="Zamówienia bez dokumentu WZ" rows={filter(data?.pending||[])} columns={[['order_no','Zamówienie'],['customer','Klient'],['product_names','Produkt'],['ordered_quantity','Ilość'],['status','Status'],['order_date','Data utworzenia'],['age_days','Wiek (dni)']]}/></>}
 {tab==='orders'&&<DataTable title="Zamówienia z dopasowanymi wysyłkami" rows={filter(data?.matched||[])} columns={[['order_no','Zamówienie'],['customer','Klient'],['product_names','Produkt'],['ordered_quantity','Zamówiono'],['shipped_quantity','Wysłano'],['deviation_pct','Odchylenie %'],['assessment','Ocena'],['status','Status']]}/>} 
 {tab==='shipments'&&<DataTable title="Wysyłki poza zestawieniem" rows={data?.unmatched||[]} columns={[['document_no','Dokument WZ'],['order_ref','Zamówienie'],['customer','Klient'],['product_name','Produkt'],['shipped_quantity','Ilość'],['loading_date','Data'],['reason','Powód']]}/>} 
 {tab==='agents'&&<div className="agentLayout"><section className="agentMain card"><div className="agentHeader"><span className="agentOrb"><Bot/></span><div><small>AGENT KOORDYNUJĄCY</small><h2>Operations Intelligence</h2><p>Deleguje analizę do agentów ryzyka, finansowego i jakości danych.</p></div><i className="online">ONLINE</i></div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><b>{m.role==='assistant'?'Agent AI':'Ty'}</b><p>{m.text}</p>{m.meta&&<small>{m.meta}</small>}</div>)}{busy&&<div className="thinking">Agenci analizują Supabase…</div>}</div><div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)}/><button disabled={busy} onClick={ask}><Sparkles size={18}/>Uruchom zespół</button></div></section><aside className="agentTeam card"><span>PRAWDZIWE NARZĘDZIA</span><div className="toolInfo"><Database/><b>Jedno źródło prawdy</b><p>Agenci korzystają z tej samej logiki dopasowania, tolerancji i niedowozów co dashboard.</p></div></aside></div>}
 {tab==='data'&&<div className="dataGrid"><section className="drop card"><span className="dropIcon"><FileUp/></span><h2>Wgraj dane wejściowe</h2><p>Zamówienia, wysyłki i granice tolerancji są rozpoznawane po nagłówkach i zapisywane bezpośrednio w Supabase.</p><label className="upload big">Wybierz pliki<input type="file" multiple accept=".xlsx,.xls" onChange={e=>importFiles(e.target.files)}/></label>{importText&&<div className="importStatus ok">{importText}</div>}</section><section className="card"><h2>Kontrola wsadu</h2><p className="muted">Zamówienia dopasowane: {fmt(k.matched_orders)}</p><p className="muted">Bez wysyłki: {fmt(k.pending_orders)}</p><p className="muted">Wysyłki niedopasowane: {fmt(k.unmatched_shipments)}</p><p className="muted">Reguły tolerancji: {fmt(data?.tolerances?.length)}</p></section></div>}
 </section></main>
}
function K({label,value,good,warn}:any){return <article className="kpi"><span>{label}</span><b className={good?'good':warn?'warn':''}>{value}</b></article>}
function DataTable({title,rows,columns}:{title:string;rows:any[];columns:string[][]}){return <section className="records card"><div className="recordsHead"><div><span>DANE Z SUPABASE</span><h2>{title}</h2></div><b>{fmt(rows.length)} rekordów</b></div><div className="tableScroll"><table><thead><tr>{columns.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=>{let v=r[c[0]];if(Array.isArray(v))v=v.join(', ');if(c[0].includes('date')&&v)v=String(v).slice(0,10);if(c[0].includes('pct')&&v!=null)v=pct(Number(v));if(typeof v==='number'&&!c[0].includes('pct'))v=fmt(v);return <td key={c[0]}>{String(v??'—')}</td>})}</tr>)}</tbody></table></div></section>}
function Login({onLogin}:{onLogin:(e:string,p:string,s?:boolean)=>Promise<void>}){const[e,setE]=useState(''),[p,setP]=useState(''),[err,setErr]=useState('');async function go(s=false){try{setErr('');await onLogin(e,p,s)}catch(x){setErr(x instanceof Error?x.message:'Nie udało się zalogować')}}return <div className="login"><div className="loginBox"><span className="agentOrb"><BrainCircuit/></span><p>FLOWCONTROL AI</p><h1>Zaloguj się do centrum operacyjnego</h1><input value={e} onChange={x=>setE(x.target.value)} placeholder="E-mail"/><input value={p} onChange={x=>setP(x.target.value)} type="password" placeholder="Hasło"/>{err&&<em>{err}</em>}<button onClick={()=>go(false)}>Zaloguj się</button><button className="secondary" onClick={()=>go(true)}>Utwórz konto</button></div></div>}
