'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,Bot,BrainCircuit,Database,FileUp,LogOut,PackageCheck,ShieldAlert,Sparkles,Truck,TriangleAlert,Clock3} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {browserSupabase,configured} from '@/lib/supabase';

const fmt=(v:number)=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:1}).format(v||0);
const pct=(v:number|null)=>v==null?'—':new Intl.NumberFormat('pl-PL',{style:'percent',maximumFractionDigits:1}).format(v);
type Msg={role:'user'|'assistant';text:string;meta?:string};

export default function OperationsDashboard(){
 const [ready,setReady]=useState(!configured),[email,setEmail]=useState(''),[tab,setTab]=useState('overview'),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [from,setFrom]=useState('2026-01-01'),[to,setTo]=useState('2026-12-31'),[customer,setCustomer]=useState(''),[assessment,setAssessment]=useState('');
 const [messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'Jestem koordynatorem. Korzystam z tej samej warstwy obliczeń co dashboard: zamówienia, wysyłki, tolerancje, niedowozy i zamówienia bez wysyłki.'}]),[question,setQuestion]=useState('Podsumuj realizację zamówień od stycznia 2026 i wskaż największe ryzyka.'),[busy,setBusy]=useState(false),[importText,setImportText]=useState('');
 useEffect(()=>{const sb=browserSupabase();if(!sb)return;sb.auth.getUser().then(({data})=>{setEmail(data.user?.email||'');setReady(true)});const {data}=sb.auth.onAuthStateChange((_e,s)=>setEmail(s?.user.email||''));return()=>data.subscription.unsubscribe()},[]);
 async function refresh(){const sb=browserSupabase();if(!sb||!email)return;setLoading(true);setError('');try{const {data:s}=await sb.auth.getSession();const r=await fetch(`/api/analytics?from=${from}&to=${to}`,{headers:{Authorization:`Bearer ${s.session?.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Błąd danych')}finally{setLoading(false)}}
 useEffect(()=>{if(email)refresh()},[email]);
 async function login(e:string,p:string,signup=false){const sb=browserSupabase();if(!sb)return;const r=signup?await sb.auth.signUp({email:e,password:p}):await sb.auth.signInWithPassword({email:e,password:p});if(r.error)throw r.error}
 async function ask(){if(!question.trim()||busy)return;const q=question;setQuestion('');setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);try{const sb=browserSupabase();const {data:s}=await sb!.auth.getSession();const r=await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.session?.access_token}`},body:JSON.stringify({question:q,demo:false})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(m=>[...m,{role:'assistant',text:d.answer,meta:`${d.model} · ${d.tools?.join(' → ')||'analiza'} · ${d.latencyMs} ms`}])}catch(e){setMessages(m=>[...m,{role:'assistant',text:`Błąd analizy: ${e instanceof Error?e.message:'nieznany błąd'}`}])}finally{setBusy(false)}}
 async function importFiles(files:FileList|null){if(!files?.length)return;const sb=browserSupabase();const {data:s}=await sb!.auth.getSession();let rows=0;try{for(const file of Array.from(files)){setImportText(`Importuję ${file.name}…`);const form=new FormData();form.append('files',file);const r=await fetch('/api/import',{method:'POST',headers:{Authorization:`Bearer ${s.session?.access_token}`},body:form});const raw=await r.text();let d:any;try{d=JSON.parse(raw)}catch{throw new Error(`${file.name}: nieprawidłowa odpowiedź serwera (${r.status})`)}if(!r.ok)throw new Error(d.error||`Nie udało się wczytać ${file.name}`);rows+=Number(d.rows)||0}setImportText(`Zaimportowano ${fmt(rows)} rekordów.`);await refresh()}catch(e){setImportText(e instanceof Error?e.message:'Import nie powiódł się')}}
 async function exportXlsx(){if(!data)return;const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();const summary=[{Pozycja:'Zakres',Wartość:`${from} – ${to}`},{Pozycja:'Realizacja',Wartość:pct(data.kpis.fulfilment_rate)},{Pozycja:'Zamówiono',Wartość:data.kpis.ordered_quantity},{Pozycja:'Wysłano',Wartość:data.kpis.shipped_quantity},{Pozycja:'W granicach',Wartość:pct(data.kpis.within_rate)},{Pozycja:'Przekroczenia',Wartość:data.kpis.outside_limit}];XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary),'Podsumowanie');const rows=tab==='lost'?filter(data.lost):tab==='pending'?filter(data.pending):tab==='shipments'?data.unmatched:filter(data.matched);XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Dane');XLSX.writeFile(wb,`zamowienia_vs_wysylki_${tab}.xlsx`)}
 const customers=useMemo(()=>[...new Set((data?.clients||[]).map((x:any)=>x.customer))].sort() as string[],[data]);
 const filter=(rows:any[])=>rows.filter(r=>(!customer||r.customer===customer)&&(!assessment||r.assessment===assessment));
 if(!ready)return <div className="splash"><BrainCircuit/>Łączenie z Supabase…</div>;
 if(configured&&!email)return <Login onLogin={login}/>;
 const k=data?.kpis||{};const nav:[string,any,string][]=[['overview',Activity,'Przegląd'],['lost',TriangleAlert,'Utracone sztuki'],['pending',Clock3,'Do wysłania'],['orders',PackageCheck,'Zamówienia'],['shipments',Truck,'Wysyłki'],['agents',Bot,'Agenci AI'],['data',Database,'Źródła danych']];
 return <main><aside><div className="brand"><span><BrainCircuit/></span><div>FlowControl<b>AI</b><small>Order intelligence</small></div></div><nav>{nav.map(([id,I,label]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={19}/>{label}</button>)}</nav><div className="asideBottom"><div className="security"><ShieldAlert size={17}/>RLS · {email}</div><button onClick={()=>browserSupabase()?.auth.signOut()}><LogOut size={18}/>Wyloguj</button></div></aside><section className="workspace"><header><div><p>ZAMÓWIENIA VS WYSYŁKI</p><h1>{nav.find(x=>x[0]===tab)?.[2]}</h1></div><div className="headActions"><button className="refreshBtn" onClick={refresh}>↻ Odśwież</button><button className="exportBtn" onClick={exportXlsx}>↓ Pobierz XLSX</button><label className="upload"><FileUp size={17}/>Importuj XLSX<input type="file" multiple accept=".xlsx,.xls" onChange={e=>importFiles(e.target.files)}/></label></div></header>
 {error&&<div className="importStatus error">{error}</div>}{tab!=='agents'&&tab!=='data'&&<><div className="periodPills"><button onClick={()=>{setFrom('2026-01-01');setTo('2026-12-31')}}>Cały okres</button>{(data?.monthly||[]).map((x:any)=><button key={x.month} onClick={()=>{setFrom(`${x.month}-01`);const d=new Date(`${x.month}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);setTo(d.toISOString().slice(0,10))}}>{x.month}</button>)}</div><div className="filterbar"><label>Od <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Do <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Klient <select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Wszyscy klienci ({customers.length})</option>{customers.map(x=><option key={x}>{x}</option>)}</select></label><label>Ocena <select value={assessment} onChange={e=>setAssessment(e.target.value)}><option value="">Wszystkie</option><option>W granicach</option><option>Przekroczona nadwyżka</option><option>Przekroczony brak</option><option>Bez zdefiniowanych granic</option></select></label><button onClick={refresh}>Zastosuj zakres</button></div></>}
 {tab==='overview'&&<><div className="dbStrip"><div><small>OSTATNIE ZAMÓWIENIE W BAZIE</small><b>{data?.freshness?.last_order?.slice(0,10)||'—'}</b></div><div><small>OSTATNIA WYSYŁKA W BAZIE</small><b>{data?.freshness?.last_shipment?.slice(0,10)||'—'}</b></div><div><small>WSAD W BAZIE</small><b>{fmt(data?.database?.files)} plików</b></div><div><small>BAZA</small><b>{fmt(data?.database?.total_rows)} pozycji</b><span>{fmt(data?.database?.order_rows)} zamówień · {fmt(data?.database?.shipment_rows)} wysyłek</span></div></div><div className="kpis five"><K label="REALIZACJA" value={pct(k.fulfilment_rate)} good/><K label="ZAMÓWIONO" value={`${fmt(k.ordered_quantity)} szt.`}/><K label="WYSŁANO" value={`${fmt(k.shipped_quantity)} szt.`}/><K label="W GRANICACH" value={pct(k.within_rate)} good/><K label="PRZEKROCZENIA" value={fmt(k.outside_limit)} warn/></div><Heatmap rows={data?.client_month||[]}/></>}
 {tab==='lost'&&<DataTable title="Zamówienia z niedowozem" rows={filter(data?.lost||[])} columns={[['order_no','Zamówienie'],['customer','Klient'],['ordered_quantity','Zamówiono'],['shipped_quantity','Wysłano'],['lost_quantity','Utracone szt.'],['minimum_quantity','Dolna granica'],['lost_below_limit','Poniżej granicy'],['assessment','Ocena'],['order_date','Data zamówienia']]}/>} 
 {tab==='pending'&&<><div className="kpis"><K label="Bez wysyłki" value={fmt(k.pending_orders)}/><K label="Sztuk do wysłania" value={fmt(k.pending_quantity)} warn/><K label="Wysyłki niedopasowane" value={fmt(k.unmatched_shipments)}/><K label="Niedowozy" value={fmt(k.lost_quantity)} warn/></div><DataTable title="Zamówienia bez dokumentu WZ" rows={filter(data?.pending||[])} columns={[['order_no','Zamówienie'],['customer','Klient'],['product_names','Produkt'],['ordered_quantity','Ilość'],['status','Status'],['order_date','Data utworzenia'],['age_days','Wiek (dni)']]}/></>}
 {tab==='orders'&&<DataTable title="Zamówienia z dopasowanymi wysyłkami" rows={filter(data?.matched||[])} columns={[['order_no','Zamówienie'],['customer','Klient'],['product_names','Produkt'],['ordered_quantity','Zamówiono'],['shipped_quantity','Wysłano'],['deviation_pct','Odchylenie %'],['assessment','Ocena'],['status','Status']]}/>} 
 {tab==='shipments'&&<DataTable title="Wysyłki poza zestawieniem" rows={data?.unmatched||[]} columns={[['document_no','Dokument WZ'],['order_ref','Zamówienie'],['customer','Klient'],['product_name','Produkt'],['shipped_quantity','Ilość'],['loading_date','Data'],['reason','Powód']]}/>} 
 {tab==='agents'&&<div className="agentLayout"><section className="agentMain card"><div className="agentHeader"><span className="agentOrb"><Bot/></span><div><small>AGENT KOORDYNUJĄCY</small><h2>Operations Intelligence</h2><p>Deleguje analizę do agentów ryzyka, finansowego i jakości danych.</p></div><i className="online">ONLINE</i></div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><b>{m.role==='assistant'?'Agent AI':'Ty'}</b><p>{m.text}</p>{m.meta&&<small>{m.meta}</small>}</div>)}{busy&&<div className="thinking">Agenci analizują Supabase…</div>}</div><div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)}/><button disabled={busy} onClick={ask}><Sparkles size={18}/>Uruchom zespół</button></div></section><aside className="agentTeam card"><span>PRAWDZIWE NARZĘDZIA</span><div className="toolInfo"><Database/><b>Jedno źródło prawdy</b><p>Agenci korzystają z tej samej logiki dopasowania, tolerancji i niedowozów co dashboard.</p></div></aside></div>}
 {tab==='data'&&<div className="dataGrid"><section className="drop card"><span className="dropIcon"><FileUp/></span><h2>Wgraj dane wejściowe</h2><p>Zamówienia, wysyłki i granice tolerancji są rozpoznawane po nagłówkach i zapisywane bezpośrednio w Supabase.</p><label className="upload big">Wybierz pliki<input type="file" multiple accept=".xlsx,.xls" onChange={e=>importFiles(e.target.files)}/></label>{importText&&<div className="importStatus ok">{importText}</div>}</section><section className="card"><h2>Kontrola wsadu</h2><p className="muted">Zamówienia dopasowane: {fmt(k.matched_orders)}</p><p className="muted">Bez wysyłki: {fmt(k.pending_orders)}</p><p className="muted">Wysyłki niedopasowane: {fmt(k.unmatched_shipments)}</p><p className="muted">Reguły tolerancji: {fmt(data?.tolerances?.length)}</p></section></div>}
 </section></main>
}
function K({label,value,good,warn}:any){return <article className="kpi"><span>{label}</span><b className={good?'good':warn?'warn':''}>{value}</b></article>}
function Heatmap({rows}:{rows:any[]}){const months=[...new Set(rows.map(r=>r.month))].sort();const clients=[...new Set(rows.map(r=>r.customer))].sort();const map=new Map(rows.map(r=>[`${r.customer}\u001f${r.month}`,r.rate]));const color=(v:number|null)=>v==null?'empty':v<.98?'low':v>1.02?'high':'neutral';return <section className="heat card"><div className="cardTitle"><div><span>REALIZACJA % — KLIENT × MIESIĄC</span><h2>Wysłana ilość / ilość zamówiona × 100</h2></div></div><div className="heatScroll"><table><thead><tr><th>Klient</th>{months.map(m=><th key={m}>{m}</th>)}<th>Razem</th></tr></thead><tbody>{clients.map(c=>{const values=months.map(m=>map.get(`${c}\u001f${m}`) as number|undefined);const valid=values.filter((v):v is number=>v!=null);const avg=valid.length?valid.reduce((a,b)=>a+b,0)/valid.length:null;return <tr key={c}><th>{c}</th>{values.map((v,i)=><td key={months[i]} className={color(v??null)}>{v==null?'·':(v*100).toFixed(1)}</td>)}<td className={color(avg)}>{avg==null?'·':(avg*100).toFixed(1)}</td></tr>})}</tbody></table></div></section>}
function DataTable({title,rows,columns}:{title:string;rows:any[];columns:string[][]}){return <section className="records card"><div className="recordsHead"><div><span>DANE Z SUPABASE</span><h2>{title}</h2></div><b>{fmt(rows.length)} rekordów</b></div><div className="tableScroll"><table><thead><tr>{columns.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=>{let v=r[c[0]];if(Array.isArray(v))v=v.join(', ');if(c[0].includes('date')&&v)v=String(v).slice(0,10);if(c[0].includes('pct')&&v!=null)v=pct(Number(v));if(typeof v==='number'&&!c[0].includes('pct'))v=fmt(v);return <td key={c[0]}>{String(v??'—')}</td>})}</tr>)}</tbody></table></div></section>}
function Login({onLogin}:{onLogin:(e:string,p:string,s?:boolean)=>Promise<void>}){const[e,setE]=useState(''),[p,setP]=useState(''),[err,setErr]=useState('');async function go(s=false){try{setErr('');await onLogin(e,p,s)}catch(x){setErr(x instanceof Error?x.message:'Nie udało się zalogować')}}return <div className="login"><div className="loginBox"><span className="agentOrb"><BrainCircuit/></span><p>FLOWCONTROL AI</p><h1>Zaloguj się do centrum operacyjnego</h1><input value={e} onChange={x=>setE(x.target.value)} placeholder="E-mail"/><input value={p} onChange={x=>setP(x.target.value)} type="password" placeholder="Hasło"/>{err&&<em>{err}</em>}<button onClick={()=>go(false)}>Zaloguj się</button><button className="secondary" onClick={()=>go(true)}>Utwórz konto</button></div></div>}
