// The dashboard intentionally normalizes heterogeneous Supabase rows at runtime.
// @ts-nocheck
'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,ArrowUpRight,Bot,BrainCircuit,Database,FileUp,LogOut,PackageCheck,ShieldAlert,Sparkles,Truck} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {browserSupabase,configured} from '@/lib/supabase';
import {demoOrders,demoTrend} from '@/lib/demo';

type Msg={role:'user'|'assistant';text:string;meta?:string};
type Fulfilment={customer:string;ordered:number;shipped:number;status:string;month:string;margin:number;orderNo?:string;orderDate?:string|null};
const fmt=(n:number)=>new Intl.NumberFormat('pl-PL').format(n);
async function fetchAll(sb:any,table:string,columns:string,orderColumn:string){const rows:any[]=[];for(let from=0;;from+=1000){const {data,error}=await sb.from(table).select(columns).order(orderColumn,{ascending:false}).range(from,from+999);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<1000)break}return {data:rows,error:null}}
export default function Home(){
 const [authReady,setAuthReady]=useState(!configured),[userEmail,setUserEmail]=useState('');
 const [tab,setTab]=useState('overview'),[messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'Jestem agentem koordynującym. Mogę sam pobrać dane, przekazać analizę agentowi ryzyka lub finansowemu i zwrócić sprawdzony plan działań.'}]);
 const [question,setQuestion]=useState('Które zamówienia wymagają dziś interwencji i dlaczego?'),[busy,setBusy]=useState(false);
 const [importState,setImportState]=useState<{kind:'idle'|'busy'|'ok'|'error';text:string}>({kind:'idle',text:''});
 const [liveRows,setLiveRows]=useState<Fulfilment[]>([]),[orderRows,setOrderRows]=useState<any[]>([]),[shipmentRows,setShipmentRows]=useState<any[]>([]),[loadingData,setLoadingData]=useState(false);
 const analysisRows:Fulfilment[]=liveRows.length?liveRows:(configured?[]:demoOrders);
 const totals=useMemo(()=>analysisRows.reduce((a,r)=>({o:a.o+r.ordered,s:a.s+r.shipped}),{o:0,s:0}),[analysisRows]); const gap=totals.o-totals.s;
 const liveTrend=useMemo(()=>{if(!orderRows.length&&!shipmentRows.length)return configured?[]:demoTrend;const months=new Map<string,{m:string;zam:number;wys:number}>();const add=(date:any,key:'zam'|'wys',value:any)=>{if(!date)return;const d=new Date(date);if(Number.isNaN(d.getTime()))return;const id=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;const x=months.get(id)||{m:d.toLocaleDateString('pl-PL',{month:'short',year:'2-digit'}),zam:0,wys:0};x[key]+=Number(value)||0;months.set(id,x)};orderRows.forEach(r=>add(r.created_at_source,'zam',r.quantity));shipmentRows.forEach(r=>add(r.loading_date,'wys',r.shipped_quantity));return [...months.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([,v])=>v)},[orderRows,shipmentRows]);
 useEffect(()=>{const sb=browserSupabase();if(!sb)return;sb.auth.getUser().then(({data})=>{setUserEmail(data.user?.email||'');setAuthReady(true)});const {data}=sb.auth.onAuthStateChange((_e,s)=>setUserEmail(s?.user.email||''));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!userEmail)return;const sb=browserSupabase();if(!sb)return;setLoadingData(true);Promise.all([fetchAll(sb,'order_fulfilment','*','order_date'),fetchAll(sb,'orders','order_no,product_no,customer,product_name,quantity,order_value,currency,created_at_source,status','created_at_source'),fetchAll(sb,'shipments','document_no,order_no,order_ref,product_name,shipped_quantity,loading_date,customer','loading_date')]).then(([f,o,s])=>{let rows=(f.data||[]).map((r:any)=>({customer:r.customer||'Bez klienta',ordered:Number(r.ordered_quantity)||0,shipped:Number(r.shipped_quantity)||0,status:Number(r.short_quantity)>0?'risk':'ok',month:r.order_date?new Date(r.order_date).toLocaleDateString('pl-PL',{month:'short'}):'',margin:0,orderNo:r.order_no,orderDate:r.order_date}));if(!rows.length&&(o.data?.length||s.data?.length)){const byCustomer=new Map<string,Fulfilment>();const get=(customer:any)=>{const key=customer||'Bez klienta';if(!byCustomer.has(key))byCustomer.set(key,{customer:key,ordered:0,shipped:0,status:'ok',month:'',margin:0});return byCustomer.get(key)!};(o.data||[]).forEach((r:any)=>{const x=get(r.customer);x.ordered+=Number(r.quantity)||0;x.orderDate=r.created_at_source});(s.data||[]).forEach((r:any)=>{get(r.customer).shipped+=Number(r.shipped_quantity)||0});rows=[...byCustomer.values()].map(x=>({...x,status:x.ordered>x.shipped?'risk':'ok'}))}setLiveRows(rows);if(o.data)setOrderRows(o.data);if(s.data)setShipmentRows(s.data)}).finally(()=>setLoadingData(false))},[userEmail]);
 async function login(email:string,password:string,signup=false){const sb=browserSupabase();if(!sb)return;const r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error}
 async function ask(){if(!question.trim()||busy)return; const q=question;setMessages(m=>[...m,{role:'user',text:q}]);setQuestion('');setBusy(true);
  try{const sb=browserSupabase();const session=sb?await sb.auth.getSession():null;const token=session?.data.session?.access_token;
   const r=await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({question:q,demo:!token})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Błąd agenta');setMessages(m=>[...m,{role:'assistant',text:d.answer,meta:`${d.agent} · ${d.tools?.join(' → ')||'analiza'} · ${d.latencyMs} ms`}]);
  }catch(e){setMessages(m=>[...m,{role:'assistant',text:`Nie udało się uruchomić analizy: ${e instanceof Error?e.message:'błąd'}`}])}finally{setBusy(false)}}
 async function importFiles(files:FileList|null){if(!files?.length)return;const sb=browserSupabase();if(!sb){setImportState({kind:'error',text:'Najpierw skonfiguruj Supabase.'});return}const {data}=await sb.auth.getSession();if(!data.session){setImportState({kind:'error',text:'Sesja wygasła. Zaloguj się ponownie.'});return}const selected=Array.from(files);let rows=0,imported=0,skipped=0;try{for(let i=0;i<selected.length;i++){const file=selected[i];setImportState({kind:'busy',text:`Importowanie pliku ${i+1} z ${selected.length}: ${file.name}`});const form=new FormData();form.append('files',file);const r=await fetch('/api/import',{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`},body:form});const raw=await r.text();let out:any={};try{out=raw?JSON.parse(raw):{}}catch{throw new Error(r.status===413?`${file.name} jest za duży dla Vercel. Maksymalny rozmiar pojedynczego pliku to około 4 MB.`:`${file.name}: serwer zwrócił nieprawidłową odpowiedź (${r.status}).`)}if(!r.ok){if(out.skipped?.length){skipped++;continue}throw new Error(`${file.name}: ${out.error||'import nie powiódł się'}`)}rows+=Number(out.rows)||0;imported+=Number(out.files)||0;skipped+=out.skipped?.length||0}if(!imported)throw new Error('Nie rozpoznano żadnego pliku zamówień, wysyłek ani tolerancji.');setImportState({kind:'ok',text:`Zaimportowano ${fmt(rows)} wierszy z ${imported} plików.${skipped?` Pominięto ${skipped} nieobsługiwanych plików.`:''} Odświeżam dane…`});setTimeout(()=>window.location.reload(),1800)}catch(e){setImportState({kind:'error',text:e instanceof Error?e.message:'Import nie powiódł się.'})}}
 if(!authReady)return <div className="splash"><BrainCircuit/>Łączenie z bezpieczną bazą…</div>;
 if(configured&&!userEmail)return <Login onLogin={login}/>;
 return <main><aside><div className="brand"><span><BrainCircuit/></span><div>FlowControl<b>AI</b><small>Order intelligence</small></div></div><nav>{[['overview',Activity,'Centrum kontroli'],['orders',PackageCheck,'Zamówienia'],['shipments',Truck,'Wysyłki'],['agents',Bot,'Zespół agentów'],['data',Database,'Źródła danych']].map(([id,I,label]:any)=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I size={19}/>{label}</button>)}</nav><div className="asideBottom"><div className="security"><ShieldAlert size={17}/><span>Dane chronione przez RLS</span></div><button onClick={()=>browserSupabase()?.auth.signOut()}><LogOut size={18}/>Wyloguj</button></div></aside>
 <section className="workspace"><header><div><p>OPERATIONS COMMAND CENTER</p><h1>{tab==='agents'?'Zespół agentów AI':tab==='data'?'Źródła danych':tab==='orders'?'Zamówienia':tab==='shipments'?'Wysyłki':'Zamówienia vs wysyłki'}</h1></div><div className="headActions"><span className="live"><i/> Dane aktualne</span><label className="upload"><FileUp size={17}/>Importuj XLSX<input type="file" multiple accept=".xlsx,.xls" onChange={e=>importFiles(e.target.files)}/></label></div></header>
 {tab==='agents'?<AgentView messages={messages} q={question} setQ={setQuestion} ask={ask} busy={busy}/>:tab==='data'?<DataView onFiles={importFiles} state={importState}/>:tab==='orders'?<RecordsView title="Zamówienia" loading={loadingData} rows={orderRows} columns={[['order_no','Numer zamówienia'],['customer','Klient'],['product_name','Produkt'],['quantity','Ilość'],['created_at_source','Data'],['status','Status']]}/>:tab==='shipments'?<RecordsView title="Wysyłki" loading={loadingData} rows={shipmentRows} columns={[['document_no','Dokument WZ'],['order_no','Zamówienie'],['customer','Klient'],['product_name','Produkt'],['shipped_quantity','Wysłana ilość'],['loading_date','Data załadunku']]}/>:<><div className="notice"><Sparkles size={18}/><div><b>Agent wykrył priorytety wymagające interwencji</b><span>{liveRows.length?'Analiza oparta na danych z Supabase.':'Widok demonstracyjny — zaimportuj dane, aby uruchomić rzeczywistą analizę.'}</span></div><button onClick={()=>setTab('agents')}>Przeanalizuj <ArrowUpRight size={16}/></button></div>
 <div className="kpis"><Kpi label="Zamówiono" value={fmt(totals.o)} note="sztuk w analizowanym okresie"/><Kpi label="Wysłano" value={fmt(totals.s)} note={totals.o?`${(totals.s/totals.o*100).toFixed(1)}% realizacji`:'brak zamówień w widoku'} good/><Kpi label="Niedostarczone" value={fmt(Math.max(gap,0))} note="nie jest automatycznie utraconą sprzedażą" warn/><Kpi label="Klienci wymagający uwagi" value={String(analysisRows.filter(r=>r.status==='risk').length)} note="wyliczone z danych Supabase" warn/></div>
 <div className="grid"><article className="chart card"><div className="cardTitle"><div><span>PRZEPŁYW WOLUMENU</span><h2>Zamówienia i wysyłki</h2></div><small>tys. sztuk</small></div><ResponsiveContainer width="100%" height={260}><AreaChart data={liveTrend}><defs><linearGradient id="g1" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.35}/><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#22263b" vertical={false}/><XAxis dataKey="m" stroke="#737891"/><YAxis stroke="#737891"/><Tooltip contentStyle={{background:'#151827',border:'1px solid #30344c',borderRadius:12}}/><Area type="monotone" dataKey="zam" stroke="#8b5cf6" fill="url(#g1)" strokeWidth={3}/><Area type="monotone" dataKey="wys" stroke="#22d3a7" fill="transparent" strokeWidth={3}/></AreaChart></ResponsiveContainer></article>
 <article className="card tableCard"><div className="cardTitle"><div><span>SYGNAŁY RYZYKA</span><h2>Klienci wymagający uwagi</h2></div></div>{analysisRows.slice(0,8).map((r,i)=><div className="client" key={(r.orderNo||r.customer)+i}><span className={`dot ${r.status}`}/><div><b>{r.customer}</b><small>{fmt(r.shipped)} / {fmt(r.ordered)} szt.</small></div><strong>{r.ordered?(r.shipped/r.ordered*100).toFixed(1):'—'}%</strong></div>)}</article></div></>}
 {!configured&&<div className="demoBadge">Tryb demonstracyjny · podłącz Supabase, aby pracować na danych rzeczywistych</div>}</section></main>}
function Kpi({label,value,note,good,warn}:any){return <article className="kpi"><span>{label}</span><b className={good?'good':warn?'warn':''}>{value}</b><small>{note}</small></article>}
function Login({onLogin}:{onLogin:(e:string,p:string,s?:boolean)=>Promise<void>}){const[e,setE]=useState(''),[p,setP]=useState(''),[err,setErr]=useState('');async function go(s=false){try{setErr('');await onLogin(e,p,s)}catch(x){setErr(x instanceof Error?x.message:'Nie udało się zalogować')}}return <div className="login"><div className="loginBox"><span className="agentOrb"><BrainCircuit/></span><p>FLOWCONTROL AI</p><h1>Zaloguj się do centrum operacyjnego</h1><small>Dane są dostępne wyłącznie dla uwierzytelnionych użytkowników.</small><input value={e} onChange={x=>setE(x.target.value)} placeholder="E-mail"/><input value={p} onChange={x=>setP(x.target.value)} type="password" placeholder="Hasło (min. 6 znaków)"/>{err&&<em>{err}</em>}<button onClick={()=>go(false)}>Zaloguj się</button><button className="secondary" onClick={()=>go(true)}>Utwórz konto</button></div></div>}
function AgentView({messages,q,setQ,ask,busy}:any){return <div className="agentLayout"><section className="agentMain card"><div className="agentHeader"><span className="agentOrb"><Bot/></span><div><small>AGENT KOORDYNUJĄCY</small><h2>Operations Intelligence</h2><p>Dobiera specjalistę i sam uruchamia narzędzia analityczne.</p></div><i className="online">ONLINE</i></div><div className="messages">{messages.map((m:Msg,i:number)=><div key={i} className={`message ${m.role}`}><b>{m.role==='assistant'?'Agent AI':'Ty'}</b><p>{m.text}</p>{m.meta&&<small>{m.meta}</small>}</div>)}{busy&&<div className="thinking"><i/><i/><i/> Agenci analizują bazę…</div>}</div><div className="composer"><textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}}/><button onClick={ask} disabled={busy}><Sparkles size={18}/>Uruchom zespół</button></div></section><aside className="agentTeam card"><span>ZESPÓŁ AGENTÓW</span>{[['Koordynator','Deleguje zadania i scala odpowiedź'],['Agent ryzyka','Wykrywa niedowozy i anomalie'],['Agent finansowy','Liczy ekspozycję i marżę'],['Agent jakości danych','Sprawdza kompletność i spójność']].map((x,i)=><div className="member" key={x[0]}><i>{i+1}</i><div><b>{x[0]}</b><small>{x[1]}</small></div></div>)}<div className="toolInfo"><Database size={18}/><b>Narzędzia, nie wklejony kontekst</b><p>Agenci wykonują kontrolowane zapytania do Supabase zgodnie z uprawnieniami zalogowanego użytkownika.</p></div></aside></div>}
function DataView({onFiles,state}:{onFiles:(f:FileList|null)=>void;state:{kind:string;text:string}}){const disabled=state.kind==='busy';return <div className="dataGrid"><section className="drop card"><span className="dropIcon"><FileUp/></span><h2>Wgraj dane wejściowe</h2><p>Dodaj jeden lub kilka eksportów XLSX. System rozpozna zamówienia, wysyłki albo granice tolerancji po nagłówkach.</p><label className={`upload big ${disabled?'disabled':''}`}>{disabled?'Importowanie…':'Wybierz pliki'}<input type="file" multiple accept=".xlsx,.xls" disabled={disabled} onChange={e=>onFiles(e.target.files)}/></label>{state.text&&<div className={`importStatus ${state.kind}`}>{state.text}</div>}<small>Pliki nie są zapisywane w GitHub. Po walidacji rekordy trafiają bezpośrednio do Supabase.</small></section><section className="card rules"><span>OBSŁUGIWANE ŹRÓDŁA</span>{[['Zamówienia','Numer zamówienia MyPrint · Ilość · Klient'],['Wysyłki','Wysłana ilość · Zamówienie · Dokument'],['Granice tolerancji','KLIENT · NAKŁAD · BRAK · NADWYŻKA']].map(x=><div key={x[0]}><PackageCheck size={19}/><p><b>{x[0]}</b><small>{x[1]}</small></p></div>)}<hr/><p className="migration"><Database size={18}/><span><b>Migracja danych z poprzedniego repo</b><small>Pliki zamówień, wysyłek i tolerancji zostaną zapisane w Supabase. Pozostałe arkusze będą pominięte.</small></span></p></section></div>}
function RecordsView({title,rows,columns,loading}:{title:string;rows:any[];columns:string[][];loading:boolean}){return <section className="records card"><div className="recordsHead"><div><span>DANE Z SUPABASE</span><h2>{title}</h2></div><b>{fmt(rows.length)} rekordów</b></div>{loading?<p className="empty">Pobieranie danych…</p>:rows.length?<div className="tableScroll"><table><thead><tr>{columns.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={c[0]}>{c[0].includes('date')&&r[c[0]]?new Date(r[c[0]]).toLocaleDateString('pl-PL'):typeof r[c[0]]==='number'?fmt(r[c[0]]):String(r[c[0]]??'—')}</td>)}</tr>)}</tbody></table></div>:<p className="empty">Brak danych. Przejdź do „Źródła danych” i zaimportuj pliki XLSX.</p>}</section>}
