'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,ArrowUpRight,Bot,BrainCircuit,Database,FileUp,LogOut,PackageCheck,ShieldAlert,Sparkles,Truck} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {browserSupabase,configured} from '@/lib/supabase';
import {demoOrders,demoTrend} from '@/lib/demo';

type Msg={role:'user'|'assistant';text:string;meta?:string};
const fmt=(n:number)=>new Intl.NumberFormat('pl-PL').format(n);
export default function Home(){
 const [authReady,setAuthReady]=useState(!configured),[userEmail,setUserEmail]=useState('');
 const [tab,setTab]=useState('overview'),[messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'Jestem agentem koordynującym. Mogę sam pobrać dane, przekazać analizę agentowi ryzyka lub finansowemu i zwrócić sprawdzony plan działań.'}]);
 const [question,setQuestion]=useState('Które zamówienia wymagają dziś interwencji i dlaczego?'),[busy,setBusy]=useState(false);
 const totals=useMemo(()=>demoOrders.reduce((a,r)=>({o:a.o+r.ordered,s:a.s+r.shipped}),{o:0,s:0}),[]); const gap=totals.o-totals.s;
 useEffect(()=>{const sb=browserSupabase();if(!sb)return;sb.auth.getUser().then(({data})=>{setUserEmail(data.user?.email||'');setAuthReady(true)});const {data}=sb.auth.onAuthStateChange((_e,s)=>setUserEmail(s?.user.email||''));return()=>data.subscription.unsubscribe()},[]);
 async function login(email:string,password:string,signup=false){const sb=browserSupabase();if(!sb)return;const r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error}
 async function ask(){if(!question.trim()||busy)return; const q=question;setMessages(m=>[...m,{role:'user',text:q}]);setQuestion('');setBusy(true);
  try{const sb=browserSupabase();const session=sb?await sb.auth.getSession():null;const token=session?.data.session?.access_token;
   const r=await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({question:q,demo:!token})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Błąd agenta');setMessages(m=>[...m,{role:'assistant',text:d.answer,meta:`${d.agent} · ${d.tools?.join(' → ')||'analiza'} · ${d.latencyMs} ms`}]);
  }catch(e){setMessages(m=>[...m,{role:'assistant',text:`Nie udało się uruchomić analizy: ${e instanceof Error?e.message:'błąd'}`}])}finally{setBusy(false)}}
 async function importFiles(files:FileList|null){if(!files?.length)return;const sb=browserSupabase();if(!sb){alert('Najpierw skonfiguruj Supabase.');return}const {data}=await sb.auth.getSession();if(!data.session){alert('Zaloguj się przed importem.');return}const form=new FormData();Array.from(files).forEach(f=>form.append('files',f));const r=await fetch('/api/import',{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`},body:form});const out=await r.json();alert(r.ok?`Import zakończony: ${out.rows} wierszy z ${out.files} plików.`:out.error)}
 if(!authReady)return <div className="splash"><BrainCircuit/>Łączenie z bezpieczną bazą…</div>;
 if(configured&&!userEmail)return <Login onLogin={login}/>;
 return <main><aside><div className="brand"><span><BrainCircuit/></span><div>FlowControl<b>AI</b><small>Order intelligence</small></div></div><nav>{[['overview',Activity,'Centrum kontroli'],['orders',PackageCheck,'Zamówienia'],['shipments',Truck,'Wysyłki'],['agents',Bot,'Zespół agentów'],['data',Database,'Źródła danych']].map(([id,I,label]:any)=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I size={19}/>{label}</button>)}</nav><div className="asideBottom"><div className="security"><ShieldAlert size={17}/><span>Dane chronione przez RLS</span></div><button onClick={()=>browserSupabase()?.auth.signOut()}><LogOut size={18}/>Wyloguj</button></div></aside>
 <section className="workspace"><header><div><p>OPERATIONS COMMAND CENTER</p><h1>{tab==='agents'?'Zespół agentów AI':tab==='data'?'Źródła danych':'Zamówienia vs wysyłki'}</h1></div><div className="headActions"><span className="live"><i/> Dane aktualne</span><label className="upload"><FileUp size={17}/>Importuj XLSX<input type="file" multiple accept=".xlsx,.xls" onChange={e=>importFiles(e.target.files)}/></label></div></header>
 {tab==='agents'?<AgentView messages={messages} q={question} setQ={setQuestion} ask={ask} busy={busy}/>:tab==='data'?<DataView onFiles={importFiles}/>:<><div className="notice"><Sparkles size={18}/><div><b>Agent wykrył 2 priorytety wymagające interwencji</b><span>Dwaj klienci odpowiadają za 79% niedostarczonego wolumenu w danych demonstracyjnych.</span></div><button onClick={()=>setTab('agents')}>Przeanalizuj <ArrowUpRight size={16}/></button></div>
 <div className="kpis"><Kpi label="Zamówiono" value={fmt(totals.o)} note="sztuk w analizowanym okresie"/><Kpi label="Wysłano" value={fmt(totals.s)} note={`${(totals.s/totals.o*100).toFixed(1)}% realizacji`} good/><Kpi label="Niedostarczone" value={fmt(gap)} note="nie jest automatycznie utraconą sprzedażą" warn/><Kpi label="Klienci wymagający uwagi" value="2" note="priorytet wysoki" warn/></div>
 <div className="grid"><article className="chart card"><div className="cardTitle"><div><span>PRZEPŁYW WOLUMENU</span><h2>Zamówienia i wysyłki</h2></div><small>tys. sztuk</small></div><ResponsiveContainer width="100%" height={260}><AreaChart data={demoTrend}><defs><linearGradient id="g1" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.35}/><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#22263b" vertical={false}/><XAxis dataKey="m" stroke="#737891"/><YAxis stroke="#737891"/><Tooltip contentStyle={{background:'#151827',border:'1px solid #30344c',borderRadius:12}}/><Area type="monotone" dataKey="zam" stroke="#8b5cf6" fill="url(#g1)" strokeWidth={3}/><Area type="monotone" dataKey="wys" stroke="#22d3a7" fill="transparent" strokeWidth={3}/></AreaChart></ResponsiveContainer></article>
 <article className="card tableCard"><div className="cardTitle"><div><span>SYGNAŁY RYZYKA</span><h2>Klienci wymagający uwagi</h2></div></div>{demoOrders.map(r=><div className="client" key={r.customer}><span className={`dot ${r.status}`}/><div><b>{r.customer}</b><small>{fmt(r.shipped)} / {fmt(r.ordered)} szt.</small></div><strong>{(r.shipped/r.ordered*100).toFixed(1)}%</strong></div>)}</article></div></>}
 {!configured&&<div className="demoBadge">Tryb demonstracyjny · podłącz Supabase, aby pracować na danych rzeczywistych</div>}</section></main>}
function Kpi({label,value,note,good,warn}:any){return <article className="kpi"><span>{label}</span><b className={good?'good':warn?'warn':''}>{value}</b><small>{note}</small></article>}
function Login({onLogin}:{onLogin:(e:string,p:string,s?:boolean)=>Promise<void>}){const[e,setE]=useState(''),[p,setP]=useState(''),[err,setErr]=useState('');async function go(s=false){try{setErr('');await onLogin(e,p,s)}catch(x){setErr(x instanceof Error?x.message:'Nie udało się zalogować')}}return <div className="login"><div className="loginBox"><span className="agentOrb"><BrainCircuit/></span><p>FLOWCONTROL AI</p><h1>Zaloguj się do centrum operacyjnego</h1><small>Dane są dostępne wyłącznie dla uwierzytelnionych użytkowników.</small><input value={e} onChange={x=>setE(x.target.value)} placeholder="E-mail"/><input value={p} onChange={x=>setP(x.target.value)} type="password" placeholder="Hasło (min. 6 znaków)"/>{err&&<em>{err}</em>}<button onClick={()=>go(false)}>Zaloguj się</button><button className="secondary" onClick={()=>go(true)}>Utwórz konto</button></div></div>}
function AgentView({messages,q,setQ,ask,busy}:any){return <div className="agentLayout"><section className="agentMain card"><div className="agentHeader"><span className="agentOrb"><Bot/></span><div><small>AGENT KOORDYNUJĄCY</small><h2>Operations Intelligence</h2><p>Dobiera specjalistę i sam uruchamia narzędzia analityczne.</p></div><i className="online">ONLINE</i></div><div className="messages">{messages.map((m:Msg,i:number)=><div key={i} className={`message ${m.role}`}><b>{m.role==='assistant'?'Agent AI':'Ty'}</b><p>{m.text}</p>{m.meta&&<small>{m.meta}</small>}</div>)}{busy&&<div className="thinking"><i/><i/><i/> Agenci analizują bazę…</div>}</div><div className="composer"><textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}}/><button onClick={ask} disabled={busy}><Sparkles size={18}/>Uruchom zespół</button></div></section><aside className="agentTeam card"><span>ZESPÓŁ AGENTÓW</span>{[['Koordynator','Deleguje zadania i scala odpowiedź'],['Agent ryzyka','Wykrywa niedowozy i anomalie'],['Agent finansowy','Liczy ekspozycję i marżę'],['Agent jakości danych','Sprawdza kompletność i spójność']].map((x,i)=><div className="member" key={x[0]}><i>{i+1}</i><div><b>{x[0]}</b><small>{x[1]}</small></div></div>)}<div className="toolInfo"><Database size={18}/><b>Narzędzia, nie wklejony kontekst</b><p>Agenci wykonują kontrolowane zapytania do Supabase zgodnie z uprawnieniami zalogowanego użytkownika.</p></div></aside></div>}
function DataView({onFiles}:{onFiles:(f:FileList|null)=>void}){return <div className="dataGrid"><section className="drop card"><span className="dropIcon"><FileUp/></span><h2>Wgraj dane wejściowe</h2><p>Dodaj jeden lub kilka eksportów XLSX. System rozpozna zamówienia, wysyłki albo granice tolerancji po nagłówkach.</p><label className="upload big">Wybierz pliki<input type="file" multiple accept=".xlsx,.xls" onChange={e=>onFiles(e.target.files)}/></label><small>Pliki nie są zapisywane w GitHub. Po walidacji rekordy trafiają bezpośrednio do Supabase.</small></section><section className="card rules"><span>OBSŁUGIWANE ŹRÓDŁA</span>{[['Zamówienia','Numer zamówienia MyPrint · Ilość · Klient'],['Wysyłki','Wysłana ilość · Zamówienie · Dokument'],['Granice tolerancji','KLIENT · NAKŁAD · BRAK · NADWYŻKA']].map(x=><div key={x[0]}><PackageCheck size={19}/><p><b>{x[0]}</b><small>{x[1]}</small></p></div>)}<hr/><p className="migration"><Database size={18}/><span><b>Migracja danych z poprzedniego repo</b><small>Skrypt migracyjny może jednorazowo przesłać wszystkie pliki z katalogu „Dane wsadowe” tym samym bezpiecznym procesem importu.</small></span></p></section></div>}
