const norm=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
const baseOrder=(v:unknown)=>String(v??'').trim().match(/^(\d+\/\d{4})/)?.[1]||String(v??'').trim();
const num=(v:unknown)=>Number(v)||0;

async function paged(sb:any,table:string,columns:string,dateColumn?:string,start?:string|null,end?:string|null){
 const rows:any[]=[];
 for(let from=0;;from+=1000){let q=sb.from(table).select(columns).range(from,from+999);if(dateColumn&&start)q=q.gte(dateColumn,start);if(dateColumn&&end){const d=new Date(`${end}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);q=q.lt(dateColumn,d.toISOString())}const {data,error}=await q;if(error)throw error;rows.push(...(data||[]));if(!data||data.length<1000)break}
 return rows;
}

function band(text:string,quantity:number){const n=[...text.matchAll(/\d[\d ]*/g)].map(x=>Number(x[0].replace(/\s/g,'')));const t=norm(text);if(t.includes('powyzej'))return quantity>=(n[0]||0);if(t.startsWith('do '))return quantity<=(n[0]||Infinity);if(n.length>=2)return quantity>=n[0]&&quantity<=n[1];return !n.length||quantity>=n[0]}

export async function buildOperationalSnapshot(sb:any,startDate?:string|null,endDate?:string|null){
 const [orderRows,shipmentRows,tolerances,batches]=await Promise.all([
  paged(sb,'orders','order_no,customer,product_name,quantity,order_value,currency,created_at_source,customer_date,status','created_at_source',startDate,endDate),
  paged(sb,'shipments','document_no,order_no,order_ref,customer,product_name,shipped_quantity,loading_date','loading_date',startDate,endDate),
  paged(sb,'tolerances','customer,volume_band,shortage_pct,surplus_pct,notes'),
  paged(sb,'import_batches','file_name,file_type,row_count,status,created_at')
 ]);
 const excluded=new Set(['usuniete','usunięte','anulowany','anulowane']);
 const orders=new Map<string,any>();
 for(const r of orderRows){if(excluded.has(norm(r.status)))continue;const key=baseOrder(r.order_no);const x=orders.get(key)||{order_no:key,customer:r.customer||'Bez klienta',product_names:new Set<string>(),ordered_quantity:0,order_value:0,currency:r.currency||null,order_date:r.created_at_source,customer_date:r.customer_date,status:r.status};x.ordered_quantity+=num(r.quantity);x.order_value+=num(r.order_value);if(r.product_name)x.product_names.add(r.product_name);if(!x.order_date||r.created_at_source<x.order_date)x.order_date=r.created_at_source;orders.set(key,x)}
 const ships=new Map<string,any>();const unmatched:any[]=[];
 for(const r of shipmentRows){if(r.shipped_quantity==null)continue;const key=baseOrder(r.order_no||r.order_ref);const x=ships.get(key)||{order_no:key,shipped_quantity:0,documents:new Set<string>(),first_shipment:r.loading_date,last_shipment:r.loading_date,customer:r.customer};x.shipped_quantity+=num(r.shipped_quantity);if(r.document_no)x.documents.add(r.document_no);if(r.loading_date&&(!x.first_shipment||r.loading_date<x.first_shipment))x.first_shipment=r.loading_date;if(r.loading_date&&(!x.last_shipment||r.loading_date>x.last_shipment))x.last_shipment=r.loading_date;ships.set(key,x);if(!orders.has(key))unmatched.push({...r,reason:'Brak dopasowanego aktywnego zamówienia'})}
 const rules=tolerances.map((r:any)=>({...r,key:norm(r.customer)}));
 const matched:any[]=[];const pending:any[]=[];
 for(const [key,o] of orders){const s=ships.get(key);if(!s){pending.push({...o,product_names:[...o.product_names],age_days:o.order_date?Math.max(0,Math.floor((Date.now()-new Date(o.order_date).getTime())/86400000)):null});continue}const rule=rules.find((r:any)=>r.key===norm(o.customer)&&band(r.volume_band||'-',o.ordered_quantity));const shortage=rule?.shortage_pct==null?null:Math.abs(num(rule.shortage_pct));const surplus=rule?.surplus_pct==null?null:Math.abs(num(rule.surplus_pct));const deviation=o.ordered_quantity?s.shipped_quantity/o.ordered_quantity-1:null;let assessment='W granicach';if(!rule)assessment='Bez zdefiniowanych granic';else if(deviation!=null&&shortage!=null&&deviation < -shortage)assessment='Przekroczony brak';else if(deviation!=null&&surplus!=null&&deviation > surplus)assessment='Przekroczona nadwyżka';matched.push({...o,product_names:[...o.product_names],shipped_quantity:s.shipped_quantity,deviation_quantity:s.shipped_quantity-o.ordered_quantity,deviation_pct:deviation,assessment,shortage_pct:shortage,surplus_pct:surplus,minimum_quantity:shortage==null?null:o.ordered_quantity*(1-shortage),lost_quantity:Math.max(o.ordered_quantity-s.shipped_quantity,0),lost_below_limit:shortage==null?null:Math.max(o.ordered_quantity*(1-shortage)-s.shipped_quantity,0),shipment_count:s.documents.size,documents:[...s.documents],first_shipment:s.first_shipment,last_shipment:s.last_shipment})}
 const clientMap=new Map<string,any>();for(const r of matched){const x=clientMap.get(r.customer)||{customer:r.customer,orders:0,ordered_quantity:0,shipped_quantity:0,lost_quantity:0,outside_limit:0};x.orders++;x.ordered_quantity+=r.ordered_quantity;x.shipped_quantity+=r.shipped_quantity;x.lost_quantity+=r.lost_quantity;if(r.assessment==='Poza granicą')x.outside_limit++;clientMap.set(r.customer,x)}
 const monthMap=new Map<string,any>();for(const r of orderRows){if(!r.created_at_source)continue;const m=String(r.created_at_source).slice(0,7);const x=monthMap.get(m)||{month:m,ordered:0,shipped:0};x.ordered+=num(r.quantity);monthMap.set(m,x)}for(const r of shipmentRows){if(!r.loading_date)continue;const m=String(r.loading_date).slice(0,7);const x=monthMap.get(m)||{month:m,ordered:0,shipped:0};x.shipped+=num(r.shipped_quantity);monthMap.set(m,x)}
 const cm=new Map<string,any>();for(const r of matched){const month=String(r.order_date||'').slice(0,7);if(!month)continue;const key=`${r.customer}\u001f${month}`;const x=cm.get(key)||{customer:r.customer,month,ordered:0,shipped:0};x.ordered+=r.ordered_quantity;x.shipped+=r.shipped_quantity;cm.set(key,x)}
 const ordered=matched.reduce((a,r)=>a+r.ordered_quantity,0),shipped=matched.reduce((a,r)=>a+r.shipped_quantity,0);
 const within=matched.filter(r=>r.assessment==='W granicach').length,assessed=matched.filter(r=>r.assessment!=='Bez zdefiniowanych granic').length;
 return {period:{startDate:startDate||null,endDate:endDate||null},kpis:{matched_orders:matched.length,ordered_quantity:ordered,shipped_quantity:shipped,difference_quantity:shipped-ordered,fulfilment_rate:ordered?shipped/ordered:null,within_rate:assessed?within/assessed:null,within_orders:within,assessed_orders:assessed,without_limits:matched.length-assessed,lost_quantity:matched.reduce((a,r)=>a+r.lost_quantity,0),outside_limit:matched.filter(r=>r.assessment==='Przekroczony brak'||r.assessment==='Przekroczona nadwyżka').length,pending_orders:pending.length,pending_quantity:pending.reduce((a,r)=>a+r.ordered_quantity,0),unmatched_shipments:unmatched.length},database:{files:batches.filter((x:any)=>x.status==='completed').length,order_rows:orderRows.length,shipment_rows:shipmentRows.length,total_rows:orderRows.length+shipmentRows.length},freshness:{last_order:orderRows.map(r=>r.created_at_source).filter(Boolean).sort().at(-1)||null,last_shipment:shipmentRows.map(r=>r.loading_date).filter(Boolean).sort().at(-1)||null},matched:matched.sort((a,b)=>String(b.order_date).localeCompare(String(a.order_date))),lost:matched.filter(r=>r.lost_quantity>0).sort((a,b)=>b.lost_quantity-a.lost_quantity),pending:pending.sort((a,b)=>(b.age_days||0)-(a.age_days||0)),unmatched,clients:[...clientMap.values()].sort((a,b)=>b.lost_quantity-a.lost_quantity),monthly:[...monthMap.values()].sort((a,b)=>a.month.localeCompare(b.month)),client_month:[...cm.values()].map(x=>({...x,rate:x.ordered?x.shipped/x.ordered:null})),tolerances};
}
