import {NextRequest,NextResponse} from 'next/server';
import * as XLSX from 'xlsx';
import {userSupabase} from '@/lib/supabase';
export const runtime='nodejs'; export const maxDuration=60;
const norm=(v:unknown)=>String(v??'').trim();
const num=(v:unknown)=>{const n=Number(String(v??'').replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:null};
const date=(v:unknown)=>{if(!v)return null;const d=v instanceof Date?v:new Date(String(v));return Number.isNaN(d.getTime())?null:d.toISOString()};
function kind(headers:string[]){const h=new Set(headers);if(['Numer zamówienia MyPrint','Ilość','Klient'].every(x=>h.has(x)))return'orders';if(['Wysłana ilość','Zamówienie','Dokument'].every(x=>h.has(x)))return'shipments';if(['KLIENT','NAKŁAD','BRAK','NADWYŻKA'].every(x=>h.has(x)))return'tolerances';return null}
function baseOrder(v:unknown){return norm(v).match(/^(\d+\/\d{4})/)?.[1]||norm(v)}
export async function POST(req:NextRequest){try{const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)return NextResponse.json({error:'Wymagane logowanie.'},{status:401});const sb=userSupabase(token);const {data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:'Sesja wygasła.'},{status:401});const form=await req.formData();const files=form.getAll('files').filter(x=>x instanceof File) as File[];if(!files.length)return NextResponse.json({error:'Nie wybrano plików.'},{status:400});let total=0;
 for(const file of files){if(file.size>15_000_000)throw new Error(`${file.name}: limit pliku to 15 MB`);const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const sheet=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:null});if(!rows.length)continue;const type=kind(Object.keys(rows[0]));if(!type)throw new Error(`${file.name}: nierozpoznany układ kolumn`);const {data:batch,error:bErr}=await sb.from('import_batches').insert({user_id:user.id,file_name:file.name,file_type:type,row_count:rows.length,status:'processing'}).select('id').single();if(bErr)throw bErr;
  let mapped:any[]=[];if(type==='orders')mapped=rows.map(r=>({user_id:user.id,import_batch_id:batch.id,order_no:norm(r['Numer zamówienia MyPrint']),product_no:norm(r['Numer produktu']),customer:norm(r['Klient']),product_name:norm(r['Nazwa produktu']),quantity:num(r['Ilość']),order_value:num(r['Wartość zamówienia']),currency:norm(r['Waluta']||r['Wartość zamówienia waluta'])||null,created_at_source:date(r['Data utworzenia']),customer_date:date(r['Data klienta']),status:norm(r['Status'])||null})).filter(r=>r.order_no);
  if(type==='shipments')mapped=rows.map(r=>({user_id:user.id,import_batch_id:batch.id,document_no:norm(r['Dokument']),order_ref:norm(r['Zamówienie']),order_no:baseOrder(r['Zamówienie']),product_name:norm(r['Nazwa produktu']),shipped_quantity:num(r['Wysłana ilość']),loading_date:date(r['Załadunek/dostawa']),customer:norm(r['Klient']||r['Nazwa klienta'])})).filter(r=>r.document_no);
  if(type==='tolerances')mapped=rows.map(r=>({user_id:user.id,import_batch_id:batch.id,customer:norm(r['KLIENT']),volume_band:norm(r['NAKŁAD']),shortage_pct:num(r['BRAK']),surplus_pct:num(r['NADWYŻKA']),notes:norm(r['UWAGI'])||null})).filter(r=>r.customer);
  for(let i=0;i<mapped.length;i+=500){const {error}=await sb.from(type).upsert(mapped.slice(i,i+500),{onConflict:type==='orders'?'user_id,order_no,product_no':type==='shipments'?'user_id,document_no,order_ref,product_name':'user_id,customer,volume_band'});if(error)throw error}await sb.from('import_batches').update({status:'completed'}).eq('id',batch.id);total+=mapped.length;
 }return NextResponse.json({files:files.length,rows:total});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Import nie powiódł się.'},{status:400})}}
